# Generated by Django 4.1.5 on 2023-01-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="asignee",
            new_name="assignee",
        ),
    ]
